### ISSUE TITLE
Some compile errors silently fail

### ISSUE THREAD

**Issue by cmumatt** [nanofuzz/nanofuzz#176]
Originally reported by @ZiyaoWei in issue #56. 

Minimal example tto re-create:
```TypeScript
[NaNofuzz...]
export function a(a: number): number {
  return a;
};

[NaNofuzz...]
export function b() {
   return;
}
```
Procedure:
1. Click NaNofuzz button on `a`
2. Click Test button (observe test is successful)
3. Rename function `b` to `const` & Save
4. Click Test button again (observe no response)
5. Observe in console:
    - Promise rejection error in extension host: `[Extension Host] rejected promise not handled within 1 second: TSError: Identifier expected. 'const' is a reserved word that cannot be used here.` 
    - Stack trace inside extension process: 
   ```
   TSError: Identifier expected. 'const' is a reserved word that cannot be used here.
	at createError (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:11782:14)
	at convertError (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:11900:43)
	at astConverter (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:17504:42)
	at parseWithNodeMapsInternal (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:18680:66)
	at parse5 (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:18663:21)
	at new ProgramDef (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:19486:52)
	at ProgramDef.fromModuleAndSource (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:19539:14)
	at ProgramDef.fromModule (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:19529:23)
	at _FuzzPanel._doGetValidators (/home/codespace/.vscode-remote/extensions/penrose.nanofuzz-0.3.5/build/extension/extension.js:20908:32)
    [...]
    ```

**Comment by cmumatt** [comment]
Yes, I think you tracked this one down successfully! Putting a try/catch around the `ProgramDef.fromModule` fixes it here:

```TypeScript
    [...]
    // Fuzz the function & store the results
    let program: ProgramDef;
    try {
      program = ProgramDef.fromModule(this._fuzzEnv.function.getModule());
    } catch (e: any) {
      this._errorMessage = e.message ?? "Unknown error";
      vscode.commands.executeCommand(
        telemetry.commands.logTelemetry.name,
        new telemetry.LoggerEntry(
          "FuzzPanel.parse.error",
          "Parsing program failed. Target: %s. Message: %s",
          [this.getFnRefKey(), this._errorMessage ?? "Unknown error"]
        )
      );
      vscode.window.showErrorMessage(
        `Unable to parse the source file: ${this._fuzzEnv.function.getModule()}`
      );
      return;
    }
    [...]

```
![image](https://github.com/user-attachments/assets/fae51e3b-1cbc-444c-9be7-bf74059df12f)

Clicking the add validator button in the above state yields no result, which could be better, but I guess is the same feedback we were offering previously. One way to fix it is to call `_doGetValidators` prior to calling `_doAddValidatorCmd` here:

```TypeScript
  private _setWebviewMessageListener(webview: vscode.Webview) {
        [...]
        switch (command) {
          [...]
          case "validator.add":
            this._doGetValidators(); // added
            this._doAddValidatorCmd();
            this._doGetValidators();
            break;
          [...]
```

Alternatively we could put a similar try/catch in `_doAddValidatorCmd` or, as you mentioned, try to do the catches in the FuzzPanel itself if it doesn't seem too messy.

Really good work tracking this one down!
